# -*- coding: utf-8 -*-
"""fibonacciseries12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dcQGQC0u9tFAdtQa3zANCxogkIOLaYGZ
"""

def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_list = [0, 1]
        while len(fib_list) < n:
            next_num = fib_list[-1] + fib_list[-2]
            fib_list.append(next_num)
        return fib_list

num_terms = int(input("Enter the number of Fibonacci numbers to generate: "))

result = fibonacci(num_terms)
print("Fibonacci sequence:")
print(result)