# -*- coding: utf-8 -*-
"""mostfrequentfunction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CRDV_Y-uNdceRd-5mhgeroOD2ec26Pk4
"""

def most_frequent(input_string):

    input_string = input_string.lower()

    letter_freq = {}


    for letter in input_string:
        if letter.isalpha():
            letter_freq[letter] = letter_freq.get(letter, 0) + 1


    sorted_freq = sorted(letter_freq.items(), key=lambda x: x[1], reverse=True)


    print("Output:", end=" ")
    for letter, freq in sorted_freq:
        print(f"{letter} = {freq:02d}", end=" ")

input_string = "Please enter a string Mississippi"
most_frequent(input_string)