# -*- coding: utf-8 -*-
"""positivenumbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6OqYq1-RoGMbtSwGYYBHtaA5c5d4DVJ
"""

def print_positive_numbers(numbers_list):
    positive_numbers = [num for num in numbers_list if num > 0]
    print("Output:", positive_numbers)


list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

print("Input:", list1)
print_positive_numbers(list1)

print("Input:", list2)
print_positive_numbers(list2)