# -*- coding: utf-8 -*-
"""radius of a circle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PS9KfGmWhblYeBoMYwv4pLmgEYj7iV7T
"""

radius = float(input("Input the radius of the circle: "))
area = 3.14159 * (radius ** 2)

print("The area of the circle with radius", radius, "is:", area)