# -*- coding: utf-8 -*-
"""Schooladministration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VZEUGHUkh7eBY4qALj55dyFPLCHoMMfN
"""

class Student:
    def __init__(self, student_id, name, age, grade):
        self.student_id = student_id
        self.name = name
        self.age = age
        self.grade = grade
        self.attendance = {}

    def add_attendance(self, date, status):
        self.attendance[date] = status

    def get_attendance(self):
        return self.attendance

class School:
    def __init__(self, name):
        self.name = name
        self.students = []

    def add_student(self, student):
        self.students.append(student)

    def get_student_by_id(self, student_id):
        for student in self.students:
            if student.student_id == student_id:
                return student
        return None

if __name__ == "__main__":
    school = School("Sample School")

    student1 = Student(1, "studen A", 15, 9)
    student2 = Student(2, "Student B", 16, 10)

    school.add_student(student1)
    school.add_student(student2)

    student1.add_attendance("2023-07-25", "Present")
    student1.add_attendance("2023-07-24", "Absent")

    print(student1.get_attendance())
    found_student = school.get_student_by_id(2)
    if found_student:
        print(f"Student Found: {found_student.name}")
    else:
        print("Student Not Found")